name: Artifact handling

on:
  workflow_run:
    workflows: [Java CI with maven]
    types:
      - completed
  workflow_dispatch:
    
jobs:
   
  download:
     
    runs-on: ubuntu-latest
    env: 
      CI_COMMIT_MESSAGE: Commiting generated artifact 
      CI_COMMIT_AUTHOR: Ankit Kumar
      CI_COMMIT_EMAIL: ankit.k@beehyv.com
  
    steps:
      - name: Set branch name
        run: |
          echo "BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's#refs/heads/##')" >> $GITHUB_ENV   
      - name: Download arifact from previous workflow
        uses: actions/github-script@v6
        with:
          script: |
            let allArtifacts = await github.rest.actions.listArtifactsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "artifact1-{{ env.BRANCH_NAME }}";
            })[0];

            if (matchArtifact) {
              let download = await github.rest.actions.downloadArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: matchArtifact.id,
                archive_format: 'zip',
              });

              let fs = require('fs');
              fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/artifact1.zip`, Buffer.from(download.data));
            } else {
              console.error('Artifact not found');
            }
 
      - name: upload to git branch
        run: |
             git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
             git config --global user.email "{{ env.CI_COMMIT_EMAIL }}"
             git init
             git checkout -b artefacts-store
             git add artifact1.zip
             git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
             git remote add origin https://${{secrets.ACCESS_TOKEN}}@github.com/Ankit1Kumar/hello-spring.git
             git push origin artefacts-store
             
       
