name: Artifact handling

on:
  workflow_run:
    workflows: [Java CI with maven]
    types:
      - completed
    
jobs:
   
  download:
     
    runs-on: ubuntu-latest
    env: 
      CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
      CI_COMMIT_AUTHOR: Continuous Integration
    steps:
      - uses: actions/checkout@v2
      - name: make folder
        run: mkdir -p folder && cd folder
        
      - name: Download arifact from previous workflow
        uses: actions/github-script@v6
        with:
          script: |
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });
            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "artifact1"
            })[0];
            let download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            let fs = require('fs');
            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/artifact1.zip`, Buffer.from(download.data));
 
      - name: upload to git branch
        run: |
             git checkout -b artefacts-store
             git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
             git config --global user.email "username@users.noreply.github.com"
             git add
             git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
             git push
       
