name: Artifact handling

on:
  workflow_run:
    workflows: [Java CI with mavend]
    types:
      - completed
  workflow_dispatch:
    
jobs:
   
  download:
     
    runs-on: ubuntu-latest
    env: 
      CI_COMMIT_MESSAGE: Commiting generated artifact 
      CI_COMMIT_AUTHOR: Ankit Kumar
      CI_COMMIT_EMAIL: ankit.k@beehyv.com
  
    steps:
      - name: t1
        run: |
          echo "${{ github.ref }}"
          echo "${{ github.event.workflow_run.head_branch }}"
      - name: Set branch name when workflow dispatch
        run: |
           if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
           echo "BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's#refs/heads/##')" >> $GITHUB_ENV 
           else
           echo "BRANCH_NAME=$(echo "${{ github.event.workflow_run.head_branch }}")" >> $GITHUB_ENV 
           fi
      - name: Print artifact name
        run: |
          echo "Artifact name: artifact1-${{ env.BRANCH_NAME }}"
      - name: Download arifact from previous workflow
        if: github.event_name != 'workflow_dispatch'
        uses: actions/github-script@v6
        with:
          script: |
            let allArtifacts = await github.rest.actions.listArtifactsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name = "artifact1-${{ github.event.workflow_run.head_branch }}";
            })[0];

            if (matchArtifact) {
              let download = await github.rest.actions.downloadArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: matchArtifact.id,
                archive_format: 'zip',
              });

              let fs = require('fs');
              fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/artifact1.zip`, Buffer.from(download.data));
            } else {
              console.error('Artifact not found');
            }
 
      
