name: Java CI with maven

on:
  push:
    branches: [test1]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        run: |
            mvn -B package --file pom.xml
            mkdir artifacts && cp target/*.jar artifacts
            cd artifacts 
            
      - name: Set branch name
        run: |
          echo "BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's#refs/heads/##')" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact1-${{ env.BRANCH_NAME }}
          path: artifacts/

      - name: Print artifact name
        run: |
          echo "Artifact name: artifact1--${{ env.BRANCH_NAME }}"
          
  test:
    name: Unit test1
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
     
      - name: Run Tests
        run: mvn -B test
        
        
     
