name: Trigger on File Creation

on:
  create:
    paths:
      - '.github/workflows/test.yaml' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        run: echo "testing done"
