name: Manual Trigger Workflow run

on:
  workflow_run:
    workflows: [Upload build_artifact_release]
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Echo Message copy fuile
        run: |
             cp
